# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bffb267af929c17d37dcfc0fb87208509ed46b50a4599b84f3044dd614749c3761580fab2f972e969cd1a3769e03a1465fc200f7189dea54a68abe25ef853749

test:
  secret_key_base: cd80b5c03c5a9d5b53855b872b0a7a6e7ab5b885a0d0e16be839736abe4f1641269d91d33b55bedf62362e07121cd8108583b5001a9c8dcddf782897c8662520

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
